### ISSUE TITLE
Form does not load as expected when embeded in website

### ISSUE THREAD

**Issue by sreedmigs** [GSA/touchpoints#1338]
I tried to use the "Custom button & modal on your website" delivery option to load the form with the site page. But the form loads like this, and even the icons doesnot load and throw unsafe attempt to load. Can you guys help me with any suggestions to resolve the issue
![Screenshot 2024-01-24 151333](https://github.com/GSA/touchpoints/assets/157643556/aaa62fa5-9287-45c3-b538-1f3030be5baf)

**Comment by ryanwoldatwork** [comment]
hi @sreedmigs - the custom big thumbs up/down buttons are still in development and haven't been refined, when embedded on a page.

contact me via email regarding your timeframe, and i'll see when we might ship an update

**Comment by ryanwoldatwork** [comment]
hi @sreedmigs - please take another look. big thumbs styles are now loaded when embedded.

**Comment by sreedmigs** [comment]
Hi @ryanwoldatwork - thank you for the quick response. I will check on the styles but if you check my screenshot right, the Questions/Answers for both thumbs up/down are visible without selecting either of the options when I click on the Feedback button in custom button delivery option. But the same forms works fine if I chose inline option to load the form in new window.

**Comment by sreedmigs** [comment]
> Hi @ryanwoldatwork - thank you for the quick response. I will check on the styles but if you check my screenshot right, the Questions/Answers for both thumbs up/down are visible without selecting either of the options when I click on the Feedback button in custom button delivery option. But the same forms works fine if I chose inline option to load the form in new window.

can you please help me with this request. Thank you!

**Comment by ryanwoldatwork** [comment]
Hi @sreedmigs, yes, please get in touch at feedback-analytics@gsa.gov, and we'll schedule a call/video.

**Comment by ryanwoldatwork** [comment]
Working through this issue, there is a combination of CSP policies preventing assets from loading.

The thumb styles were resolved along the way (by implementing the styles in the modal [rather than TP-hosted] version of a form)

Configure the website's CSP to allow touchpoints assets.
Alternatively, a Touchpoints script can be hosted locally and the scripts can be re-mapped to point to assets that are copied to a specific website (as opposed to loading all the assets from Touchpoints directly).
