### ISSUE TITLE
Questions on current fields/labels

### ISSUE THREAD

**Issue by RachelF** [GSA/touchpoints#589]
Hi @ryanwoldatwork, responding to your question about which data points to include.
First, I have a few questions on current fields:
1. What are office_id and suboffice_id used for?
2. Could we rename "site_owner_email" to "site_manager_email"? (gets us away from the "owner" mental model)
3. What's the "dap_gtm_code"? What's it used for?
4. What data is supposed to display for "analytics url"? (Does that support the "DAP PARAMETERS" on the statuscard?)  I like tying this to DAP in some way - what would we want to show here?
5. Finally - I'm wondering if we could consider moving away from calling it a website statuscard to a website "profile"? One of the biggest pushbacks we got when we did our initial data call and analysis of site compliance with 21cIDEA was to the representation of a red/yellow/green score. Often, sites are not in compliance because they don't have sufficient staff or resources to meet all requirements - but we might gain more buy-in if we present info in a way that's more neutral (here's a profile of the current state) rather than a score or status. We don't want to reflect poorly on the team, if they're trying to do the right thing, but haven't been properly resourced. Make sense?

**Comment by ryanwoldatwork** [comment]
Hi @RachelF - thanks for creating this issue!

`office` and `suboffice` existed in the previous sheet. It appears they are accurately labeled. The TTS Tech Portfolio just expressed a need to sort/filter for TTS web properties only, and these fields enable that question to be answered. The `_id` fields are external id fields used to link Website objects to the Organization objects (think: selecting from a dropdown, instead of typing in text).

"Site owner" copy has been updated to "Website manager."

dap_gtm_code was imported from the previous spreadsheet. If there are business questions it answers, great. If not, we can re-assess its existence as a data field.

Similar response regarding "analytics url." If there is an existing user need; a consumer of this data, then great. If not, then this might go away.

I'm open to what to call this. "Profile" is accurate.  In terms of scoring, it does make sense to re-focus on the (multiple) user's needs and experiences here.  We can support a process that is informative for website owners, and useful for general support, governance, or reporting efforts like Digital Council, Web Modernization teams, EDX, etc.

**Comment by ryanwoldatwork** [comment]
I'm going to close this issue as 1-4 have been addressed, 5 does not require action, and the Statuscard is not currently visible to users.

Generally, we're trying to steer clear of "score" - though some users continue to express the desire for a single number to measure.
